#!/usr/bin/env bash
# Copyright (c) 2016-present Knuth Project developers.
# Distributed under the MIT software license, see the accompanying
# file COPYING or http://www.opensource.org/licenses/mit-license.php.
#
# Generated headers must belong to the build directory that generated them.
#
# config.hpp and version.hpp used to be written into the source tree, which every
# build directory shares. Configuring one build then rewrote the headers another
# build was using, and that build carried on compiling against options it was
# never given — silently, with a CMakeCache still reporting the right ones. This
# script is the regression, and every check in it fails on the code that had the
# bug.
#
# Run from the repository root:  ci/check_generated_headers.sh

set -euo pipefail

readonly ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
readonly WORK="${1:-$(mktemp -d)}"
readonly VERSION="0.0.0-check"

# Spelled out rather than inherited from whatever profile the machine detected.
# The build type is not cosmetic here: cmake_layout puts the build under
# build/<build_type>, and every path below says Release. The standard is not
# cosmetic either — a runner whose detected profile is gnu17 fails to resolve the
# dependencies at all.
readonly CONAN_SETTINGS=(-pr:h "${ROOT}/ci/conan-cpp23" -s build_type=Release)

cd "${ROOT}"

fail() { echo "FAIL: $*" >&2; exit 1; }
pass() { echo "ok: $*"; }

# What the tree looks like before anything is built. The question this script
# asks is whether *building* changes it, not whether it matches HEAD — run from a
# branch under development it never does, and comparing against HEAD would report
# the author's own edits as a build writing into the source tree.
if git rev-parse --git-dir > /dev/null 2>&1; then
    git status --porcelain -- include/ CMakeLists.txt > "${WORK}/tree-before.txt"
fi

# ---------------------------------------------------------------------------
# 1. Two build directories, opposite configurations, neither disturbing the other.
#
# The order matters: ON is configured and built first, then OFF is configured and
# built, and only then is ON re-examined. Before the fix, configuring OFF rewrote
# the shared header out from under ON.
# ---------------------------------------------------------------------------
conan build . "${CONAN_SETTINGS[@]}" -o statistics_level=basic  -o with_tests=True -of "${WORK}/on"  --version="${VERSION}" --build=missing > "${WORK}/on.log"  2>&1 \
    || { cat "${WORK}/on.log"; fail "statistics_level=basic build"; }
conan build . "${CONAN_SETTINGS[@]}" -o statistics_level=off -o with_tests=True -of "${WORK}/off" --version="${VERSION}" --build=missing > "${WORK}/off.log" 2>&1 \
    || { cat "${WORK}/off.log"; fail "statistics_level=off build"; }

readonly ON_HEADER="${WORK}/on/build/Release/include/utxoz/config.hpp"
readonly OFF_HEADER="${WORK}/off/build/Release/include/utxoz/config.hpp"

[[ -f "${ON_HEADER}"  ]] || fail "no generated config.hpp in the statistics_level=basic build directory"
[[ -f "${OFF_HEADER}" ]] || fail "no generated config.hpp in the statistics_level=off build directory"

grep -q '^#define UTXOZ_STATISTICS_LEVEL 1' "${ON_HEADER}" \
    || fail "the statistics_level=basic build directory does not have statistics enabled"
grep -q '^#define UTXOZ_STATISTICS_LEVEL 0' "${OFF_HEADER}" \
    || fail "the statistics_level=off build directory does not have statistics disabled"
pass "each build directory kept its own configuration"

# ---------------------------------------------------------------------------
# 2. No build writes into the source tree.
#
# version.hpp is tracked, so before the fix this check caught it as a modified
# file — a generated header, carrying whatever version the last build used,
# waiting to be committed by accident.
# ---------------------------------------------------------------------------
[[ -e "include/utxoz/config.hpp"  ]] && fail "a build wrote include/utxoz/config.hpp into the source tree"
[[ -e "include/utxoz/version.hpp" ]] && fail "a build wrote include/utxoz/version.hpp into the source tree"
pass "the source tree has no generated headers in it"

if git rev-parse --git-dir > /dev/null 2>&1; then
    git status --porcelain -- include/ CMakeLists.txt > "${WORK}/tree-after.txt"
    if ! diff -q "${WORK}/tree-before.txt" "${WORK}/tree-after.txt" > /dev/null; then
        echo "a build changed the source tree:" >&2
        diff "${WORK}/tree-before.txt" "${WORK}/tree-after.txt" >&2 || true
        fail "building is not supposed to modify tracked files"
    fi
    pass "building changed nothing in the source tree"
fi

# ---------------------------------------------------------------------------
# 3. A stale header in the source tree cannot shadow the generated one.
#
# Not hypothetical: every working tree that predates the move still has these two
# files, ignored by git and regenerated by nobody. The header is planted after
# configure and the build is then made to recompile, which is exactly what an
# incremental rebuild after somebody else's configure looks like.
#
# The fixture is an #error rather than a marker macro. A macro would have to be
# noticed somewhere afterwards, and a define that nothing references leaves no
# trace in a compile log — the check would pass whether or not the stale header
# was read. An #error cannot be missed: if the source tree is searched first, the
# rebuild fails, here, with that text in the log.
#
# The recompile is forced from the build tree. Touching a source file would have
# this script — whose whole subject is builds not disturbing shared state —
# mutate a timestamp that every other build directory on the machine watches. A
# concurrent build would rebuild for no reason, or worse, mid-compile, and
# git status would stay clean the entire time.
# ---------------------------------------------------------------------------
trap 'rm -f "${ROOT}/include/utxoz/config.hpp"' EXIT

cat > include/utxoz/config.hpp <<'STALE'
#pragma once
#error "UTXOZ_STALE_HEADER_WAS_USED"
STALE

cmake --build "${WORK}/on/build/Release" --target clean > "${WORK}/clean.log" 2>&1 \
    || { cat "${WORK}/clean.log"; fail "clean before the stale-header rebuild"; }

if ! cmake --build "${WORK}/on/build/Release" --parallel > "${WORK}/rebuild.log" 2>&1; then
    if grep -q "UTXOZ_STALE_HEADER_WAS_USED" "${WORK}/rebuild.log"; then
        fail "the build read the stale source-tree header instead of the generated one"
    fi
    cat "${WORK}/rebuild.log"
    fail "rebuild after planting a stale header"
fi

# The generated header was not merely found; it is still the right one.
"${WORK}/on/build/Release/tests/utxoz_tests" "Reference: statistics" > "${WORK}/stale-test.log" 2>&1 \
    || { cat "${WORK}/stale-test.log"; fail "statistics test after planting a stale header"; }
pass "the generated header wins over a stale source-tree copy"

rm -f include/utxoz/config.hpp
trap - EXIT

# ---------------------------------------------------------------------------
# 4. The installed package carries both generated headers.
#
# install(DIRECTORY include/) used to ship them only because they were sitting in
# the source tree. A package missing them is not an error here; it is a broken
# #include in whoever consumes it.
# ---------------------------------------------------------------------------
cmake --install "${WORK}/on/build/Release" --prefix "${WORK}/prefix" > "${WORK}/install.log" 2>&1 \
    || { cat "${WORK}/install.log"; fail "cmake --install"; }

[[ -f "${WORK}/prefix/include/utxoz/config.hpp"  ]] || fail "the installed package has no config.hpp"
[[ -f "${WORK}/prefix/include/utxoz/version.hpp" ]] || fail "the installed package has no version.hpp"

grep -q '^#define UTXOZ_STATISTICS_LEVEL 1' "${WORK}/prefix/include/utxoz/config.hpp" \
    || fail "the installed config.hpp does not match the configuration it was built with"
grep -q "${VERSION}" "${WORK}/prefix/include/utxoz/version.hpp" \
    || fail "the installed version.hpp does not carry the version it was built with"
pass "the installed package carries both generated headers, with the right contents"

echo "all checks passed"
